import path from 'path';
import type { Issue, ScanResult, Severity } from '../types.js';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: 'CRITICAL',
  high: 'HIGH',
  medium: 'MEDIUM',
  low: 'LOW',
  info: 'INFO',
};

const SEVERITY_BADGE: Record<Severity, string> = {
  critical: '![critical](https://img.shields.io/badge/severity-critical-red)',
  high: '![high](https://img.shields.io/badge/severity-high-orange)',
  medium: '![medium](https://img.shields.io/badge/severity-medium-yellow)',
  low: '![low](https://img.shields.io/badge/severity-low-blue)',
  info: '![info](https://img.shields.io/badge/severity-info-lightgrey)',
};

function scoreBadge(score: number): string {
  const color = score >= 90 ? 'brightgreen' : score >= 70 ? 'yellow' : 'red';
  return `![score](https://img.shields.io/badge/score-${score}%2F100-${color})`;
}

function gradeBadge(grade: string): string {
  const color =
    grade === 'A' || grade === 'B' ? 'brightgreen' :
    grade === 'C' ? 'yellow' :
    'red';
  return `![grade](https://img.shields.io/badge/grade-${grade}-${color})`;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function relPath(root: string, filePath: string): string {
  return path.relative(root, filePath);
}

function renderIssueMd(issue: Issue, root: string): string {
  const lines: string[] = [];
  const loc = `${relPath(root, issue.location.file)}:${issue.location.line}`;

  lines.push(`#### ${SEVERITY_EMOJI[issue.severity]}: ${issue.message}`);
  lines.push('');
  lines.push(`- **Rule:** \`${issue.ruleId}\``);
  lines.push(`- **Location:** \`${loc}\``);
  lines.push(`- **Confidence:** ${issue.confidence}`);
  lines.push('');
  lines.push(issue.explanation);

  if (issue.impact) {
    lines.push('');
    lines.push(`**Impact:** ${issue.impact}`);
  }

  if (issue.snippet) {
    lines.push('');
    lines.push('```');
    lines.push(issue.snippet);
    lines.push('```');
  }

  if (issue.fix) {
    lines.push('');
    lines.push(`**Fix:** ${issue.fix.description}`);
    if (issue.fix.code) {
      lines.push('');
      lines.push('```javascript');
      lines.push(issue.fix.code);
      lines.push('```');
    }
  }

  if (issue.docsUrl) {
    lines.push('');
    lines.push(`[Documentation](${issue.docsUrl})`);
  }

  lines.push('');
  lines.push('---');

  return lines.join('\n');
}

export function generateMarkdownReport(result: ScanResult): string {
  const { score, issues, files, durationMs, config, root, version, timestamp } = result;
  const lines: string[] = [];

  // Header
  lines.push('# clean-slop Report');
  lines.push('');
  lines.push(`> Generated by clean-slop v${version} on ${new Date(timestamp).toUTCString()}`);
  lines.push('');

  // Score summary
  lines.push('## Score Summary');
  lines.push('');
  lines.push(`${scoreBadge(score.overall)} ${gradeBadge(score.grade)}`);
  lines.push('');
  lines.push('| Category | Score | Issues |');
  lines.push('|----------|-------|--------|');

  for (const cat of score.categories) {
    const emoji = cat.score >= 90 ? '✅' : cat.score >= 70 ? '⚠️' : '❌';
    lines.push(
      `| ${cat.category} | ${emoji} ${cat.score}/100 | ${cat.issueCount} |`,
    );
  }

  lines.push('');
  lines.push(`**Overall Score:** ${score.overall}/100 &nbsp; **Grade:** ${score.grade}`);
  lines.push('');

  const productionStatus = score.productionReady
    ? '✅ **PRODUCTION READY**'
    : '❌ **NOT PRODUCTION READY**';
  lines.push(productionStatus);
  lines.push('');

  // Severity breakdown
  const criticalIssues = issues.filter((i) => i.severity === 'critical');
  const highIssues = issues.filter((i) => i.severity === 'high');
  const mediumIssues = issues.filter((i) => i.severity === 'medium');
  const lowIssues = issues.filter((i) => i.severity === 'low');

  lines.push('## Issue Breakdown');
  lines.push('');
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${criticalIssues.length} |`);
  lines.push(`| High | ${highIssues.length} |`);
  lines.push(`| Medium | ${mediumIssues.length} |`);
  lines.push(`| Low | ${lowIssues.length} |`);
  lines.push(`| **Total** | **${issues.length}** |`);
  lines.push('');

  // Critical issues first
  if (criticalIssues.length > 0) {
    lines.push('## Critical Issues');
    lines.push('');
    for (const issue of criticalIssues) {
      lines.push(renderIssueMd(issue, root));
    }
  }

  // High issues
  if (highIssues.length > 0) {
    lines.push('## High Severity Issues');
    lines.push('');
    for (const issue of highIssues) {
      lines.push(renderIssueMd(issue, root));
    }
  }

  // Medium issues
  if (mediumIssues.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Medium Severity Issues</summary>');
    lines.push('');
    for (const issue of mediumIssues) {
      lines.push(renderIssueMd(issue, root));
    }
    lines.push('</details>');
    lines.push('');
  }

  // Low issues
  if (lowIssues.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Low Severity Issues</summary>');
    lines.push('');
    for (const issue of lowIssues) {
      lines.push(renderIssueMd(issue, root));
    }
    lines.push('</details>');
    lines.push('');
  }

  // File stats
  lines.push('## Scan Statistics');
  lines.push('');
  lines.push(`- **Files scanned:** ${files.filter((f) => !f.skipped && !f.parseError).length}`);
  lines.push(`- **Files skipped:** ${files.filter((f) => f.skipped).length}`);
  lines.push(`- **Parse errors:** ${files.filter((f) => f.parseError).length}`);
  lines.push(`- **Duration:** ${formatDuration(durationMs)}`);
  lines.push(`- **Fail threshold:** ${config.failThreshold}/100`);
  lines.push('');

  const parseErrors = files.filter((f) => f.parseError);
  if (parseErrors.length > 0) {
    lines.push('### Parse Errors');
    lines.push('');
    for (const f of parseErrors) {
      lines.push(`- \`${relPath(root, f.file)}\`: ${f.parseError}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [clean-slop](https://github.com/clean-slop/clean-slop)*');

  return lines.join('\n');
}
